---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
  labels:
    app: tomcat
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tomcat
  template:
    metadata:
      labels:
        app: tomcat
    spec:
      containers:
        - name: my-con
          image: dockerregistery511197.azurecr.io/tomcat

---

apiVersion: v1
kind: Service
metadata:
  name: my-svc
  labels:
    app: tomcat
spec:
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: tomcat
  type: LoadBalancer

---
